const VAT=0.19;
const STORAGE_KEY='mesogi-v083-build043';
const GOOGLE_SYNC_KEY='mesogi-google-sync-v1';
const GOOGLE_QUEUE_KEY='mesogi-google-sync-queue-v1';
const legacyKeys=['mesogi-v082-build04','mesogi-v08-build04','mesogi-v07'];
const unitList=['м²','м³','м.п.','шт','комплект','точка','день','час','рейс','тонна','кг','мешок','литр'];
const initialLibrary={
 workCategories:[
  {id:'WC_DEM',name:'Демонтажные работы',active:true},
  {id:'WC_GEN',name:'Общестроительные работы',active:true},
  {id:'WC_ELEC',name:'Электромонтажные работы',active:true},
  {id:'WC_PLUMB',name:'Сантехнические работы',active:true},
  {id:'WC_FIN',name:'Отделочные работы',active:true},
  {id:'WC_OPEN',name:'Окна и двери',active:true},
  {id:'WC_ADD',name:'Дополнительные работы',active:true},
  {id:'WC_OVER',name:'Накладные расходы',active:true}
 ],
 works:[
  {id:'W1',categoryId:'WC_DEM',name:'Демонтаж плитки',unit:'м²',cost:10,sell:15,active:true,recommendedMaterialIds:[]},
  {id:'W2',categoryId:'WC_DEM',name:'Демонтаж стяжки',unit:'м²',cost:10,sell:15,active:true,recommendedMaterialIds:[]},
  {id:'W3',categoryId:'WC_GEN',name:'Кладка перегородки из блока',unit:'м²',cost:20,sell:28,active:true,recommendedMaterialIds:['M4']},
  {id:'W4',categoryId:'WC_GEN',name:'Монтаж перегородки ГКЛ',unit:'м²',cost:60,sell:80,active:true,recommendedMaterialIds:[]},
  {id:'W5',categoryId:'WC_GEN',name:'Устройство цементной стяжки',unit:'м²',cost:16,sell:22,active:true,recommendedMaterialIds:['M2']},
  {id:'W6',categoryId:'WC_GEN',name:'Нанесение цементной гидроизоляции',unit:'м²',cost:10,sell:14,active:true,recommendedMaterialIds:['M3']},
  {id:'W7',categoryId:'WC_GEN',name:'Кровельные работы',unit:'м²',cost:0,sell:0,active:true,recommendedMaterialIds:[]},
  {id:'W8',categoryId:'WC_ELEC',name:'Монтаж электроточки',unit:'точка',cost:55,sell:75,active:true,recommendedMaterialIds:[]},
  {id:'W9',categoryId:'WC_PLUMB',name:'Монтаж унитаза',unit:'шт',cost:0,sell:0,active:true,recommendedMaterialIds:[]},
  {id:'W10',categoryId:'WC_FIN',name:'Укладка плитки',unit:'м²',cost:28,sell:40,active:true,recommendedMaterialIds:['M6']},
  {id:'W11',categoryId:'WC_FIN',name:'Штукатурка стен',unit:'м²',cost:13,sell:18,active:true,recommendedMaterialIds:['M5']},
  {id:'W12',categoryId:'WC_FIN',name:'Покраска стен',unit:'м²',cost:8,sell:12,active:true,recommendedMaterialIds:['M7']},
  {id:'W13',categoryId:'WC_OPEN',name:'Установка двери',unit:'шт',cost:0,sell:0,active:true,recommendedMaterialIds:[]},
  {id:'W14',categoryId:'WC_ADD',name:'Дополнительная работа',unit:'комплект',cost:0,sell:0,active:true,recommendedMaterialIds:[]},
  {id:'W15',categoryId:'WC_OVER',name:'SKIP / контейнер',unit:'рейс',cost:210,sell:210,active:true,recommendedMaterialIds:[]},
  {id:'W16',categoryId:'WC_OVER',name:'Доставка',unit:'рейс',cost:0,sell:0,active:true,recommendedMaterialIds:[]},
  {id:'W17',categoryId:'WC_OVER',name:'Аренда оборудования',unit:'день',cost:0,sell:0,active:true,recommendedMaterialIds:[]},
  {id:'W18',categoryId:'WC_OVER',name:'Биотуалет',unit:'месяц',cost:0,sell:0,active:true,recommendedMaterialIds:[]}
 ],
 suppliers:[{id:'S1',name:'House of Materials'},{id:'S2',name:'Local Supplier Paphos'},{id:'S3',name:'Roma House'}],
 materials:[
  {id:'M1',category:'Грунтовки',manufacturer:'Mapei',name:'Primer G',unit:'литр',buyInc:6.50,supplierId:'S1',effectiveDate:'2026-07-01',active:true},
  {id:'M2',category:'Стяжки',manufacturer:'Mapei',name:'Topcem Pronto',unit:'мешок',buyInc:14.90,supplierId:'S1',effectiveDate:'2026-07-01',active:true},
  {id:'M3',category:'Гидроизоляция',manufacturer:'Sika',name:'Sikalastic-152',unit:'комплект',buyInc:54.00,supplierId:'S2',effectiveDate:'2026-07-01',active:true},
  {id:'M4',category:'Кладочные смеси',manufacturer:'Marmoline',name:'Mortar 330',unit:'мешок',buyInc:8.80,supplierId:'S2',effectiveDate:'2026-07-01',active:true},
  {id:'M5',category:'Штукатурки',manufacturer:'Knauf',name:'MP 75',unit:'мешок',buyInc:11.90,supplierId:'S3',effectiveDate:'2026-07-01',active:true},
  {id:'M6',category:'Клеи',manufacturer:'Kerakoll',name:'H40',unit:'мешок',buyInc:17.50,supplierId:'S1',effectiveDate:'2026-07-01',active:true},
  {id:'M7',category:'Краски',manufacturer:'Vivechrom',name:'Interior Emulsion',unit:'литр',buyInc:7.20,supplierId:'S2',effectiveDate:'2026-07-01',active:true}
 ]
};
let state={project:{company:'ESTUDIO MISOGI',name:'Tala Villa',client:'Новый клиент',address:'Tala, Paphos',estimateNo:'EST-2026-015',defaultMargin:25},sections:[],workLog:[],library:structuredClone(initialLibrary)};
let activeSection=null,editingWorkId=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0)+' €';
const round2=n=>Math.round((Number(n)||0)*100)/100;
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const byId=(arr,id)=>arr.find(x=>x.id===id);
const categoryName=id=>byId(state.library.workCategories,id)?.name||'';
const supplierName=id=>byId(state.library.suppliers,id)?.name||'';
function openModal(id){$('#'+id).classList.add('open')}
function closeModals(){$$('.modal').forEach(x=>x.classList.remove('open'))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1700)}
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function syncConfig(){try{return JSON.parse(localStorage.getItem(GOOGLE_SYNC_KEY))||{url:'',token:''}}catch(e){return{url:'',token:''}}}
function pendingSync(){try{return JSON.parse(localStorage.getItem(GOOGLE_QUEUE_KEY))||[]}catch(e){return[]}}
function queueForSync(action,payload){const queue=pendingSync();queue.push({action,...payload,queuedAt:new Date().toISOString()});localStorage.setItem(GOOGLE_QUEUE_KEY,JSON.stringify(queue));flushMaterialQueue()}
function queueMaterialForSync(material){queueForSync('upsertMaterial',{material})}
function queueWorkForSync(work){queueForSync('upsertWork',{work})}
function materialPayload(m){return{id:String(m.googleId||m.id),name:m.name,category:m.category,packaging:m.packaging||'',packQuantity:m.packQuantity||1,unit:m.unit,priceExVat:round2(m.priceExVat),vat:m.vat??VAT,consumption:m.consumption||0,consumptionUnit:m.consumptionUnit||'',supplier:m.supplier||supplierName(m.supplierId)||'',note:m.note||''}}
function workPayload(w){return{id:String(w.googleId||w.id),category:categoryName(w.categoryId),name:w.name,unit:w.unit,cost:round2(w.cost),sell:round2(w.sell),active:w.active!==false,note:w.note||''}}
function googleJsonp(url){return new Promise((resolve,reject)=>{const callback='mesogiSync_'+Date.now()+'_'+Math.random().toString(36).slice(2);const cleanup=()=>{delete window[callback];script.remove()};const script=document.createElement('script');const timer=setTimeout(()=>{cleanup();reject(new Error('Google timeout'))},12000);window[callback]=data=>{clearTimeout(timer);cleanup();resolve(data)};script.onerror=()=>{clearTimeout(timer);cleanup();reject(new Error('Google load failed'))};script.src=url+(url.includes('?')?'&':'?')+'callback='+callback;document.head.appendChild(script)})}
async function loadMaterialsFromGoogle(){const c=syncConfig();if(!c.url||!c.token)return;state.library.materials=state.library.materials.filter(m=>!/^M[1-7]$/.test(String(m.id)));renderMaterialsLibrary();try{const sep=c.url.includes('?')?'&':'?';const data=await googleJsonp(`${c.url}${sep}action=materials&token=${encodeURIComponent(c.token)}`);if(!Array.isArray(data.materials))throw new Error('No materials');state.library.materials=state.library.materials.filter(m=>!String(m.id).startsWith('GS_')&&!/^M[1-7]$/.test(String(m.id)));data.materials.forEach(raw=>{const id='GS_'+raw.id;let supplier=state.library.suppliers.find(s=>s.name===raw.supplier);if(!supplier&&raw.supplier){supplier={id:'GS_S_'+uid(),name:raw.supplier};state.library.suppliers.push(supplier)}state.library.materials.push({id,googleId:raw.id,category:raw.category||'Прочие материалы',manufacturer:'',name:raw.name,unit:raw.unit||'шт',buyInc:round2(raw.unitPriceIncVat||raw.priceIncVat),supplierId:supplier?.id||'',effectiveDate:new Date().toISOString().slice(0,10),active:true,packaging:raw.packaging,packQuantity:raw.packQuantity,priceExVat:round2(raw.priceExVat),vat:raw.vat,consumption:raw.consumption,consumptionUnit:raw.consumptionUnit,note:raw.note})});persist();render();toast('Материалы загружены из Google');}catch(e){console.warn('Google materials sync failed',e);renderMaterialsLibrary();toast('Не удалось загрузить материалы из Google')}}
async function loadWorkLogFromGoogle(){const c=syncConfig();if(!c.url)return;try{const sep=c.url.includes('?')?'&':'?';const data=await googleJsonp(`${c.url}${sep}action=workLog&token=${encodeURIComponent(c.token)}`);if(Array.isArray(data.entries)){state.workLog=data.entries;persist();renderWorkLog()}}catch(e){console.warn('Google work log sync failed',e)}}
async function loadWorksFromGoogle(){const c=syncConfig();if(!c.url||!c.token)return;try{const sep=c.url.includes('?')?'&':'?';const data=await googleJsonp(`${c.url}${sep}action=works&token=${encodeURIComponent(c.token)}`);if(!Array.isArray(data.works))return;const categories=new Map(state.library.workCategories.map(x=>[x.name,x]));state.library.works=data.works.map(raw=>{let category=categories.get(raw.category);if(!category){category={id:'WC_'+uid(),name:raw.category||'Дополнительные работы',active:true};state.library.workCategories.push(category);categories.set(category.name,category)}return{id:'GW_'+raw.id,googleId:raw.id,categoryId:category.id,name:raw.name,unit:raw.unit||'м²',cost:round2(raw.cost),sell:round2(raw.sell),active:raw.active!==false,note:raw.note||'',recommendedMaterialIds:[]}});persist();renderWorksLibrary();}catch(e){console.warn('Google works sync failed',e)}}
async function flushMaterialQueue(){if(!navigator.onLine)return;const c=syncConfig();const queue=pendingSync();if(!c.url||!c.token||!queue.length)return;const rest=[];for(const item of queue){try{const sep=c.url.includes('?')?'&':'?';let query;if(item.action==='upsertMaterial')query=`action=upsertMaterial&token=${encodeURIComponent(c.token)}&material=${encodeURIComponent(JSON.stringify(item.material))}`;else if(item.action==='upsertWork')query=`action=upsertWork&token=${encodeURIComponent(c.token)}&work=${encodeURIComponent(JSON.stringify(item.work))}`;else if(item.action==='upsertWorkLog')query=`action=upsertWorkLog&token=${encodeURIComponent(c.token)}&entry=${encodeURIComponent(JSON.stringify(item.entry))}`;else throw new Error('Unsupported queued action');const data=await googleJsonp(`${c.url}${sep}${query}`);if(!data||!data.ok)throw new Error('Google response failed')}catch(e){rest.push(item)}}localStorage.setItem(GOOGLE_QUEUE_KEY,JSON.stringify(rest));if(!rest.length)toast('Правки отправлены в Google')}
function openSyncSettings(){const c=syncConfig();$('#syncUrl').value=c.url||'';$('#syncToken').value=c.token||'';$('#syncStatus').textContent=c.url?'Подключение сохранено в этом браузере.':'Подключение ещё не настроено.';openModal('syncSettingsModal')}
function migrateWork(w){
 const buyInc=Number(w.buyIncSnapshot??w.buyInc??0); const matMargin=Number(w.materialMarginSnapshot??w.materialMargin??0);
 const sellInc=Number(w.materialSellIncSnapshot??w.materialSellInc??(buyInc*(1+matMargin/100)));
 return {...w,
  name:w.nameSnapshot||w.name||'', unit:w.unitSnapshot||w.unit||'м²', qty:Number(w.qty||0),
  workCost:Number(w.workCostSnapshot??w.workCost??0), workMargin:Number(w.workMarginSnapshot??w.workMargin??0),
  workSell:Number(w.workSellSnapshot??w.workSell??0), materialName:w.materialNameSnapshot||w.materialName||'',
  materialQty:Number(w.materialQty||0),materialUnit:w.materialUnitSnapshot||w.materialUnit||'шт',
  buyInc,materialMargin:matMargin,materialSellInc:sellInc,comment:w.comment||''
 };
}
function normalizeSections(){
 const standard=new Set(['Демонтажные работы','Общестроительные работы','Электромонтажные работы','Сантехнические работы','Отделочные работы','Окна и двери','Дополнительные работы','Накладные расходы']);
 const result=[]; const seen=new Map();
 for(const sec of state.sections||[]){
  const name=String(sec.name||'').trim(); if(!name)continue;
  const key=name.toLowerCase();
  if(standard.has(name)&&seen.has(key)){
   const target=seen.get(key); target.works.push(...(sec.works||[])); target.open=target.open||sec.open;
  }else{
   const clean={...sec,name,works:sec.works||[]}; result.push(clean); seen.set(key,clean);
  }
 }
 state.sections=result;
}
function restore(){
 for(const key of [STORAGE_KEY,...legacyKeys]){try{const s=JSON.parse(localStorage.getItem(key));if(!s)continue;
  if(s.sections){state.sections=(s.sections||[]).map(sec=>({...sec,works:(sec.works||[]).map(migrateWork)}));}
  if(Array.isArray(s.workLog))state.workLog=s.workLog;
  if(s.project)state.project={...state.project,...s.project};
  if(s.library?.works)state.library=structuredClone(initialLibrary);
  if(Array.isArray(s.overhead)&&s.overhead.length){let sec=state.sections.find(x=>x.name==='Накладные расходы');if(!sec){sec={id:uid(),name:'Накладные расходы',open:true,works:[]};state.sections.push(sec)}s.overhead.forEach(x=>sec.works.push(migrateWork({id:x.id||uid(),name:x.name,unit:'комплект',qty:1,workCost:x.amount,workMargin:0,workSell:x.amount})))}
  normalizeSections(); persist(); break;
 }catch(e){}}
}
function calcWork(w){const q=+w.qty||0;const workClient=(+w.workSell||0)*q;const matClient=(+w.materialSellInc||0)*(+w.materialQty||0);const cost=(+w.workCost||0)*q+(+w.buyInc||0)*(+w.materialQty||0);return{workClient,matClient,total:workClient+matClient,cost}}
function totals(){let t={work:0,materials:0,cost:0};state.sections.forEach(s=>s.works.forEach(w=>{const c=calcWork(w);t.work+=c.workClient;t.materials+=c.matClient;t.cost+=c.cost}));t.total=t.work+t.materials;t.profit=t.total-t.cost;t.margin=t.total?100*t.profit/t.total:0;t.vat=t.materials*VAT/(1+VAT);return t}
function updateProjectHeader(){ $('#projectTitle').textContent=state.project.name; $('#projectMeta').textContent=`${state.project.estimateNo} · ${state.project.client} · ${state.project.address}` }
function recalc(){const t=totals();$('#sumWork').textContent=money(t.work);$('#sumMaterials').textContent=money(t.materials);$('#sumProfit').textContent=money(t.profit);$('#sumMargin').textContent=`Фактическая маржа ${t.margin.toFixed(1)}%`;$('#sumTotal').textContent=money(t.total);$('#sumVat').textContent=`В том числе НДС по материалам ${money(t.vat)}`;renderMaterials();persist()}
function render(){updateProjectHeader();const box=$('#estimateList');box.innerHTML='';$('#emptyState').classList.toggle('hidden',state.sections.length>0);$('#sectionCount').textContent=`${state.sections.length} ${state.sections.length===1?'раздел':'разделов'}`;state.sections.forEach((s,idx)=>{const st=s.works.reduce((a,w)=>a+calcWork(w).total,0);const el=document.createElement('section');el.className='section '+(s.open?'open':'');el.dataset.id=s.id;el.innerHTML=`<div class="section-head"><button class="section-toggle">›</button><div class="section-name">${s.name}</div><div class="section-total">${money(st)}</div><button class="section-actions" title="Удалить раздел">×</button></div><div class="section-body"><div class="work-row header"><div>Наименование</div><div>Кол-во</div><div>Ед.</div><div>Работа / ед.</div><div>Материалы</div><div>Итого</div><div></div></div><div class="rows"></div><div class="add-work-row"><button>+ Добавить работу</button></div></div>`;const rows=el.querySelector('.rows');s.works.forEach(w=>{const c=calcWork(w);const r=document.createElement('div');r.className='work-row editable';r.dataset.id=w.id;r.title='Нажмите, чтобы открыть и изменить работу';r.innerHTML=`<div class="work-name"><b>${w.name}</b>${w.materialName?`<small>${w.materialName}: ${w.materialQty} ${w.materialUnit}</small>`:'<small>Нажмите строку для редактирования</small>'}${w.comment?`<small>${w.comment}</small>`:''}</div><div>${w.qty}</div><div>${w.unit}</div><div class="money">${money(w.workSell)}</div><div class="money">${money(c.matClient)}</div><div class="money">${money(c.total)}</div><button class="delete" title="Удалить">×</button>`;r.onclick=e=>{if(e.target.classList.contains('delete'))return;showWork(s.id,w.id)};r.querySelector('.delete').onclick=e=>{e.stopPropagation();s.works=s.works.filter(x=>x.id!==w.id);render()};rows.appendChild(r)});el.querySelector('.section-toggle').onclick=()=>{s.open=!s.open;render()};el.querySelector('.section-actions').onclick=()=>{if(confirm('Удалить раздел и все его работы?')){state.sections=state.sections.filter(x=>x.id!==s.id);render()}};el.querySelector('.add-work-row button').onclick=()=>showWork(s.id);box.appendChild(el)});recalc()}
function renderMaterials(){const body=$('#materialsBody');body.innerHTML='';const mats=[];state.sections.forEach(s=>s.works.forEach(w=>{if(w.materialName&&w.materialQty>0)mats.push(w)}));$('#materialsEmpty').classList.toggle('hidden',mats.length>0);mats.forEach(w=>{const total=(+w.materialSellInc||0)*(+w.materialQty||0);const tr=document.createElement('tr');tr.innerHTML=`<td>${w.materialName}</td><td>${w.materialQty}</td><td>${w.materialUnit}</td><td>${money(w.buyInc)}</td><td>${Number(w.materialMargin||0).toFixed(1)}%</td><td>${money(w.materialSellInc)}</td><td>${money(total)}</td>`;body.appendChild(tr)})}
function sectionCategoryId(name){return state.library.workCategories.find(c=>c.name===name)?.id||''}
function populateMaterials(){const sel=$('#materialLibrarySelect');sel.innerHTML='<option value="">Без материала</option>'+state.library.materials.filter(x=>x.active).map(m=>`<option value="${m.id}">${m.manufacturer} ${m.name}</option>`).join('')}
function renderCatalog(){const q=$('#workSearch').value.toLowerCase();const section=state.sections.find(x=>x.id===activeSection);const catId=sectionCategoryId(section?.name||'');const box=$('#workCatalog');box.innerHTML='';state.library.works.filter(w=>w.active&&(!catId||w.categoryId===catId)&&w.name.toLowerCase().includes(q)).forEach(w=>{const b=document.createElement('button');b.type='button';b.className='catalog-item';b.innerHTML=`<span>${w.name}</span><span>${money(w.sell)}/${w.unit}</span>`;b.onclick=()=>selectLibraryWork(w);box.appendChild(b)});if(!box.children.length)box.innerHTML='<div class="empty small-empty">В этом разделе пока нет подходящих работ. Используйте «Вручную».</div>'}
function showWork(sectionId,workId=null){activeSection=sectionId;editingWorkId=workId;const s=state.sections.find(x=>x.id===sectionId);resetWork();$('#workSectionId').value=sectionId;$('#workSectionName').textContent=s.name;$('#workModalTitle').textContent=workId?'Редактировать работу':'Добавить работу';$('#workSubmitBtn').textContent=workId?'Сохранить изменения':'Добавить работу';renderCatalog();populateMaterials();if(workId)fillFormFromWork(s.works.find(x=>x.id===workId));openModal('workModal')}
function selectLibraryWork(w){$('#workForm').dataset.workId=w.id;$('#workName').value=w.name;$('#workUnit').value=w.unit;$('#workCost').value=w.cost;$('#workSell').value=w.sell;$('#workMargin').value=w.cost?((w.sell/w.cost-1)*100).toFixed(2):0;const recommended=w.recommendedMaterialIds?.[0];if(recommended){$('#materialLibrarySelect').value=recommended;selectLibraryMaterial(byId(state.library.materials,recommended))}}
function selectLibraryMaterial(m){if(!m)return;$('#workForm').dataset.materialId=m.id;$('#materialLibrarySelect').value=m.id;$('#materialUnit').value=m.unit;$('#buyInc').value=round2(m.buyInc).toFixed(2);syncMaterial()}
function resetWork(){$('#workForm').reset();delete $('#workForm').dataset.workId;delete $('#workForm').dataset.materialId;$('#workQty').value=1;$('#workMargin').value=state.project.defaultMargin||25;$('#materialMargin').value=0;$('#workSell').value=0;$('#sellInc').value=0;$('#workSearch').value=''}
function fillFormFromWork(w){if(!w)return;$('#workName').value=w.name||'';$('#workUnit').value=w.unit||'м²';$('#workQty').value=w.qty||0;$('#workCost').value=w.workCost||0;$('#workMargin').value=w.workMargin||0;$('#workSell').value=w.workSell||0;$('#materialQty').value=w.materialQty||0;$('#materialUnit').value=w.materialUnit||'шт';$('#buyInc').value=w.buyInc||0;$('#materialMargin').value=w.materialMargin||0;$('#sellInc').value=w.materialSellInc||0;$('#workComment').value=w.comment||'';if(w.workId)$('#workForm').dataset.workId=w.workId;if(w.materialId){$('#workForm').dataset.materialId=w.materialId;$('#materialLibrarySelect').value=w.materialId}}
function syncMaterial(){const inc=round2($('#buyInc').value),m=+$('#materialMargin').value||0;$('#sellInc').value=round2(inc*(1+m/100)).toFixed(2)}
function renderWorksLibrary(filter=''){const body=$('#worksLibraryBody');body.innerHTML='';const q=filter.toLowerCase();state.library.works.filter(x=>x.name.toLowerCase().includes(q)).forEach(w=>{const tr=document.createElement('tr');tr.className='editable';tr.title='Двойной клик — редактировать работу';tr.innerHTML=`<td>${categoryName(w.categoryId)}</td><td>${w.name}</td><td>${w.unit}</td><td>${money(w.sell)}</td><td><span class="status-pill ${w.active?'':'off'}">${w.active?'Активна':'Неактивна'}</span></td>`;tr.ondblclick=()=>openEditLibraryWork(w);body.appendChild(tr)})}
let materialClickTimer=null;
function renderMaterialsLibrary(filter=''){const body=$('#materialsLibraryBody');body.innerHTML='';const c=syncConfig();if(!c.url||!c.token){const tr=document.createElement('tr');tr.innerHTML='<td colspan="7"><div class="empty"><b>Справочник ещё не подключён к Google Таблицам</b><span>Учебные материалы не показываются. Откройте «Настройки», вставьте URL синхронизации и код доступа, затем сохраните.</span><button class="primary" id="openSyncFromMaterials">Открыть настройки</button></div></td>';body.appendChild(tr);$('#openSyncFromMaterials').onclick=()=>{closeModals();openSyncSettings()};return}const q=filter.toLowerCase();const materials=state.library.materials.filter(m=>!/^M[1-7]$/.test(String(m.id)));if(!materials.length){const tr=document.createElement('tr');tr.innerHTML='<td colspan="7"><div class="empty"><b>Загружаем материалы из Google Таблицы…</b><span>Если список не появится, проверьте URL и код доступа в «Настройках».</span></div></td>';body.appendChild(tr);return}materials.filter(x=>(x.name+' '+x.manufacturer).toLowerCase().includes(q)).forEach(m=>{const tr=document.createElement('tr');const pack=[m.packaging,m.packQuantity?`${m.packQuantity} ${m.unit}`:''].filter(Boolean).join(', ')||m.unit;tr.innerHTML=`<td>${m.category}</td><td>${m.manufacturer} ${m.name}</td><td>${pack}</td><td>${money(m.buyInc)}</td><td>${supplierName(m.supplierId)}</td><td>${m.effectiveDate}</td><td><span class="status-pill ${m.active?'':'off'}">${m.active?'Активен':'Неактивен'}</span></td>`;tr.className='editable';tr.title='Один клик — добавить в смету; двойной — редактировать';tr.onclick=()=>{clearTimeout(materialClickTimer);materialClickTimer=setTimeout(()=>useMaterialInEstimate(m),220)};tr.ondblclick=()=>{clearTimeout(materialClickTimer);openEditLibraryMaterial(m)};body.appendChild(tr)})}
function useMaterialInEstimate(m){if(!state.sections.length){toast('Сначала добавьте раздел сметы');return}const openForSection=s=>{closeModals();showWork(s.id);selectLibraryMaterial(m);$('#materialQty').value=1;$('#workName').value=m.name;$('#workQty').value=1;$('#workName').focus();toast('Укажите название работы и сохраните строку')};if(state.sections.length===1){openForSection(state.sections[0]);return}const box=$('#sectionOptions');box.innerHTML='';state.sections.forEach(s=>{const b=document.createElement('button');b.textContent=s.name;b.onclick=()=>openForSection(s);box.appendChild(b)});openModal('sectionModal')}
function renderWorkLog(){const body=$('#workLogBody');if(!body)return;body.innerHTML='';const entries=[...(state.workLog||[])].sort((a,b)=>String(b.date).localeCompare(String(a.date)));$('#workLogEmpty').classList.toggle('hidden',entries.length>0);entries.forEach(x=>{const row=document.createElement('tr');row.innerHTML=`<td>${x.date||''}</td><td>${x.object||''}</td><td>${x.worker||''}</td><td>${x.work||''}</td><td>${Number(x.hours||0)}</td><td>${x.status||''}</td><td>${x.note||''}</td>`;body.appendChild(row)})}
function openWorkLog(){renderWorkLog();$('#logDate').value=new Date().toISOString().slice(0,10);$('#logObject').value=state.project.name||'';openModal('workLogModal')}
let editingLibraryWorkId=null,editingLibraryMaterialId=null;
function openLibraryWorkEditor(work=null){editingLibraryWorkId=work?.id||null;const select=$('#libraryWorkCategory');select.innerHTML=state.library.workCategories.map(c=>`<option value="${c.id}">${c.name}</option>`).join('');$('#workLibraryEditorTitle').textContent=work?'Редактировать работу':'Новая работа';$('#workLibraryEditorSubmit').textContent=work?'Сохранить изменения':'Добавить работу';$('#libraryWorkCategory').value=work?.categoryId||state.library.workCategories[1].id;$('#libraryWorkName').value=work?.name||'';$('#libraryWorkUnit').value=work?.unit||'м²';$('#libraryWorkCost').value=work?.cost||0;$('#libraryWorkSell').value=work?.sell||0;$('#libraryWorkActive').value=String(work?.active!==false);$('#libraryWorkNote').value=work?.note||'';openModal('workLibraryEditorModal');$('#libraryWorkName').focus()}
function addLibraryWork(){openLibraryWorkEditor()}
function openEditLibraryWork(work){openLibraryWorkEditor(work)}
function saveLibraryWork(){const name=$('#libraryWorkName').value.trim();if(!name)return;const existing=state.library.works.find(w=>w.id===editingLibraryWorkId);const work={id:existing?.id||uid(),googleId:existing?.googleId||'',categoryId:$('#libraryWorkCategory').value,name,unit:$('#libraryWorkUnit').value.trim()||'м²',cost:round2($('#libraryWorkCost').value),sell:round2($('#libraryWorkSell').value),active:$('#libraryWorkActive').value==='true',note:$('#libraryWorkNote').value.trim(),recommendedMaterialIds:existing?.recommendedMaterialIds||[]};if(existing)Object.assign(existing,work);else state.library.works.push(work);persist();queueWorkForSync(workPayload(work));closeModals();renderWorksLibrary($('#worksLibrarySearch').value);toast(existing?'Работа изменена':'Работа добавлена')}
function openAddLibraryMaterial(){editingLibraryMaterialId=null;$('#materialEditorTitle').textContent='Новый материал';$('#materialEditorHelp').textContent='Материал появится в справочнике и будет поставлен в очередь синхронизации.';$('#materialEditorSubmit').textContent='Добавить материал';$('#addMaterialForm').reset();$('#newMaterialPackQty').value=1;$('#newMaterialUnit').value='шт';$('#newMaterialConsumptionUnit').value='';$('#newMaterialVat').value=VAT;$('#newMaterialPriceExVat').value=0;$('#newMaterialConsumption').value=0;openModal('addMaterialModal')}
function openEditLibraryMaterial(m){editingLibraryMaterialId=m.id;$('#materialEditorTitle').textContent='Редактировать материал';$('#materialEditorHelp').textContent='Изменения будут отправлены в Google Таблицы.';$('#materialEditorSubmit').textContent='Сохранить изменения';$('#newMaterialName').value=m.name||'';$('#newMaterialCategory').value=m.category||'';$('#newMaterialSupplier').value=m.supplier||supplierName(m.supplierId)||'';$('#newMaterialPackaging').value=m.packaging||'';$('#newMaterialPackQty').value=m.packQuantity||1;$('#newMaterialUnit').value=m.unit||'шт';$('#newMaterialPriceExVat').value=round2(m.priceExVat);$('#newMaterialVat').value=m.vat??VAT;$('#newMaterialConsumption').value=m.consumption||0;$('#newMaterialConsumptionUnit').value=m.consumptionUnit||'';$('#newMaterialNote').value=m.note||'';openModal('addMaterialModal')}
function addLibraryMaterial(){const name=$('#newMaterialName').value.trim();if(!name)return;const supplierNameValue=$('#newMaterialSupplier').value.trim();let supplier=state.library.suppliers.find(s=>s.name.toLowerCase()===supplierNameValue.toLowerCase());if(supplierNameValue&&!supplier){supplier={id:uid(),name:supplierNameValue};state.library.suppliers.push(supplier)}const priceExVat=round2($('#newMaterialPriceExVat').value),vat=Number($('#newMaterialVat').value)||0;const existing=state.library.materials.find(m=>m.id===editingLibraryMaterialId);const material={id:existing?.id||uid(),googleId:existing?.googleId||'',category:$('#newMaterialCategory').value.trim()||'Прочие материалы',manufacturer:'',name,packaging:$('#newMaterialPackaging').value.trim(),packQuantity:Number($('#newMaterialPackQty').value)||1,unit:$('#newMaterialUnit').value.trim()||'шт',priceExVat,vat,buyInc:round2(priceExVat*(1+vat)),consumption:Number($('#newMaterialConsumption').value)||0,consumptionUnit:$('#newMaterialConsumptionUnit').value.trim(),supplierId:supplier?.id||'',supplier:supplierNameValue,note:$('#newMaterialNote').value.trim(),effectiveDate:existing?.effectiveDate||new Date().toISOString().slice(0,10),active:existing?.active!==false};if(existing)Object.assign(existing,material);else state.library.materials.push(material);persist();queueMaterialForSync(materialPayload(material));closeModals();renderMaterialsLibrary($('#materialsLibrarySearch').value);toast(existing?'Материал изменён':'Материал добавлен в справочник')}
$('#addSectionBtn').onclick=()=>{renderSectionOptions();openModal('sectionModal')};$('#projectBtn').onclick=()=>{$('#projectCompany').value=state.project.company;$('#projectName').value=state.project.name;$('#projectClient').value=state.project.client;$('#projectAddress').value=state.project.address;$('#projectMargin').value=state.project.defaultMargin;openModal('projectModal')};$('#saveBtn').onclick=()=>{persist();toast('Смета сохранена в браузере')};$$('[data-close]').forEach(b=>b.onclick=closeModals);$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)closeModals()});
const sectionCategories=['Демонтажные работы','Общестроительные работы','Электромонтажные работы','Сантехнические работы','Отделочные работы','Окна и двери','Дополнительные работы','Накладные расходы'];
function renderSectionOptions(){const box=$('#sectionOptions');box.innerHTML='';const used=new Set(state.sections.map(s=>s.name));sectionCategories.filter(name=>!used.has(name)).forEach(name=>{const b=document.createElement('button');b.textContent=name;b.onclick=()=>{const sec={id:uid(),name,open:true,works:[]};state.sections.push(sec);persist();closeModals();render();showWork(sec.id)};box.appendChild(b)});const custom=document.createElement('button');custom.textContent='Новый раздел вручную';custom.onclick=()=>{const name=(prompt('Название раздела')||'').trim();if(!name)return;if(state.sections.some(s=>s.name.toLowerCase()===name.toLowerCase())){toast('Такой раздел уже добавлен');return}state.sections.push({id:uid(),name,open:true,works:[]});persist();closeModals();render()};box.appendChild(custom)};
$('#manualWorkBtn').onclick=()=>{$('#workForm').dataset.workId='';$('#workName').value='';$('#workName').focus()};$('#workSearch').oninput=renderCatalog;$('#materialLibrarySelect').onchange=()=>{const m=byId(state.library.materials,$('#materialLibrarySelect').value);if(m)selectLibraryMaterial(m);else{delete $('#workForm').dataset.materialId;$('#materialQty').value=0;$('#buyInc').value=0;$('#sellInc').value=0}};
$('#workCost').oninput=()=>{const c=+$('#workCost').value||0,m=+$('#workMargin').value||0;$('#workSell').value=(c*(1+m/100)).toFixed(2)};$('#workMargin').oninput=$('#workCost').oninput;$('#buyInc').oninput=syncMaterial;$('#materialMargin').oninput=syncMaterial;
$('#workForm').onsubmit=e=>{e.preventDefault();const s=state.sections.find(x=>x.id===$('#workSectionId').value);if(!s)return;const selectedWork=byId(state.library.works,$('#workForm').dataset.workId);const selectedMat=byId(state.library.materials,$('#workForm').dataset.materialId);const existing=editingWorkId?s.works.find(x=>x.id===editingWorkId):null;const w={id:existing?.id||uid(),workId:selectedWork?.id||existing?.workId||null,name:$('#workName').value.trim(),unit:$('#workUnit').value,qty:+$('#workQty').value||0,workCost:+$('#workCost').value||0,workMargin:+$('#workMargin').value||0,workSell:+$('#workSell').value||0,materialId:selectedMat?.id||null,materialName:selectedMat?`${selectedMat.manufacturer} ${selectedMat.name}`:'',materialQty:+$('#materialQty').value||0,materialUnit:$('#materialUnit').value,buyInc:+$('#buyInc').value||0,materialMargin:+$('#materialMargin').value||0,materialSellInc:+$('#sellInc').value||0,comment:$('#workComment').value.trim(),createdAt:existing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(!w.name)return;if(existing)Object.assign(existing,w);else s.works.push(w);s.open=true;editingWorkId=null;closeModals();render();toast(existing?'Работа изменена':'Работа добавлена')};
$('#projectForm').onsubmit=e=>{e.preventDefault();state.project.company=$('#projectCompany').value.trim();state.project.name=$('#projectName').value.trim();state.project.client=$('#projectClient').value.trim();state.project.address=$('#projectAddress').value.trim();state.project.defaultMargin=+$('#projectMargin').value||25;closeModals();render();toast('Объект обновлён')};
$('#syncSettingsForm').onsubmit=e=>{e.preventDefault();const url=$('#syncUrl').value.trim(),token=$('#syncToken').value.trim();localStorage.setItem(GOOGLE_SYNC_KEY,JSON.stringify({url,token}));closeModals();loadMaterialsFromGoogle();loadWorksFromGoogle();loadWorkLogFromGoogle();flushMaterialQueue();toast('Синхронизация сохранена')};
$('#workLogForm').onsubmit=e=>{e.preventDefault();const entry={id:'LOG-'+uid(),date:$('#logDate').value,object:$('#logObject').value.trim(),worker:$('#logWorker').value.trim(),work:$('#logWork').value.trim(),hours:+$('#logHours').value||0,status:$('#logStatus').value,note:$('#logNote').value.trim()};if(!entry.date||!entry.object||!entry.worker||!entry.work)return;state.workLog.push(entry);persist();renderWorkLog();queueForSync('upsertWorkLog',{entry});e.target.reset();$('#logDate').value=new Date().toISOString().slice(0,10);$('#logHours').value=8;toast('Запись добавлена в журнал')};
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');['estimate','materials'].forEach(t=>$('#'+t+'Tab').classList.toggle('hidden',b.dataset.tab!==t))});
$('#search').oninput=e=>{const q=e.target.value.toLowerCase();$$('.section').forEach(el=>{const s=state.sections.find(x=>x.id===el.dataset.id);el.style.display=(s.name.toLowerCase().includes(q)||s.works.some(w=>w.name.toLowerCase().includes(q)))?'':'none'})};
$('#menuBtn').onclick=()=>{$('#sidebar').classList.add('open');$('#overlay').classList.add('open')};$('#moreBtn').onclick=$('#menuBtn').onclick;$('#overlay').onclick=()=>{$('#sidebar').classList.remove('open');$('#overlay').classList.remove('open')};
$('#worksLibraryLink').onclick=e=>{e.preventDefault();renderWorksLibrary();openModal('worksLibraryModal')};$('#materialsLibraryLink').onclick=e=>{e.preventDefault();renderMaterialsLibrary();openModal('materialsLibraryModal')};$('#worksLibrarySearch').oninput=e=>renderWorksLibrary(e.target.value);$('#materialsLibrarySearch').oninput=e=>renderMaterialsLibrary(e.target.value);$('#addLibraryWorkBtn').onclick=addLibraryWork;$('#addLibraryMaterialBtn').onclick=openAddLibraryMaterial;$('#workLibraryEditorForm').onsubmit=e=>{e.preventDefault();saveLibraryWork()};$('#addMaterialForm').onsubmit=e=>{e.preventDefault();addLibraryMaterial()};
$('#workLogLink').onclick=e=>{e.preventDefault();openWorkLog()};
$('#settingsLink').onclick=e=>{e.preventDefault();openSyncSettings()};
window.addEventListener('online',flushMaterialQueue);
restore();render();loadMaterialsFromGoogle();loadWorksFromGoogle();loadWorkLogFromGoogle();

